// <auto-generated />
using System;
using CityUtilities.PointOfSaleSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CityUtilities.PointOfSaleSystem.Data.Migrations
{
    [DbContext(typeof(PointOfSaleContext))]
    [Migration("20210824193131_TestingSeededEnumWithNewProductLocation")]
    partial class TestingSeededEnumWithNewProductLocation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CityUtilities.PointOfSaleSystem.Core.Aisle", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Aisle");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "A"
                        },
                        new
                        {
                            Id = 2,
                            Title = "B"
                        },
                        new
                        {
                            Id = 3,
                            Title = "C"
                        },
                        new
                        {
                            Id = 4,
                            Title = "D"
                        },
                        new
                        {
                            Id = 5,
                            Title = "E"
                        },
                        new
                        {
                            Id = 6,
                            Title = "F"
                        },
                        new
                        {
                            Id = 7,
                            Title = "G"
                        });
                });

            modelBuilder.Entity("CityUtilities.PointOfSaleSystem.Core.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("StockNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("CityUtilities.PointOfSaleSystem.Core.ProductLocation", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("AisleId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "AisleId");

                    b.HasIndex("AisleId");

                    b.ToTable("ProductLocation");
                });

            modelBuilder.Entity("CityUtilities.PointOfSaleSystem.Core.SalesOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SaleDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SalesOrder");
                });

            modelBuilder.Entity("CityUtilities.PointOfSaleSystem.Core.SalesOrderProduct", b =>
                {
                    b.Property<int>("SalesOrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("SalesOrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("SalesOrderProduct");
                });

            modelBuilder.Entity("CityUtilities.PointOfSaleSystem.Core.ProductLocation", b =>
                {
                    b.HasOne("CityUtilities.PointOfSaleSystem.Core.Aisle", "Aisle")
                        .WithMany()
                        .HasForeignKey("AisleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CityUtilities.PointOfSaleSystem.Core.Product", "Product")
                        .WithMany("ProductLocations")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aisle");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CityUtilities.PointOfSaleSystem.Core.SalesOrderProduct", b =>
                {
                    b.HasOne("CityUtilities.PointOfSaleSystem.Core.Product", "Product")
                        .WithMany("SalesOrders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CityUtilities.PointOfSaleSystem.Core.SalesOrder", "SalesOrder")
                        .WithMany("Products")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("CityUtilities.PointOfSaleSystem.Core.Product", b =>
                {
                    b.Navigation("ProductLocations");

                    b.Navigation("SalesOrders");
                });

            modelBuilder.Entity("CityUtilities.PointOfSaleSystem.Core.SalesOrder", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
